//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by win32rc.rc
//
#define IDR_MENU1                       101
#define QSPLAT_ICON                     104
#define QSPLAT_FRAMERATE_CONTROL        107
#define QSPLAT_ABOUT_DIALOG             124
#define FRAMERATE_TEXT                  1012
#define FRAMERATE_SLIDER                1015
#define QSPLAT_OPTIONS_SHINY            40001
#define QSPLAT_OPTIONS_BACKFACECULL     40002
#define QSPLAT_COMMANDS_FULLSCREEN      40003
#define QSPLAT_COMMANDS_RESET           40004
#define QSPLAT_EXIT                     40006
#define QSPLAT_OPEN                     40007
#define QSPLAT_COMMANDS_NORMSCREEN      40008
#define QSPLAT_SET_FRAMERATE            40009
#define QSPLAT_ABOUT                    40010
#define QSPLAT_OPTIONS_SHOWLIGHT        40011
#define QSPLAT_OPTIONS_SHOWPROGRESS     40029
#define QSPLAT_OPTIONS_AUTOSPIN         40030
#define QSPLAT_ABOUT_MODEL              40034
#define QSPLAT_DRIVERS_OPENGL_POINTS    50000
#define QSPLAT_DRIVERS_OPENGL_CIRCLES   50001
#define QSPLAT_DRIVERS_OPENGL_QUADS     50002
#define QSPLAT_DRIVERS_OPENGL_POLY_CIRC 50003
#define QSPLAT_DRIVERS_OPENGL_POLY_ELLIPSES 50004
#define QSPLAT_DRIVERS_OPENGL_POLY_ELLIPSE_SMALL 50005
#define QSPLAT_DRIVERS_OPENGL_SPHERES   50006
#define QSPLAT_DRIVERS_SOFTWARE_GLDRAWPIXELS 50007
#define QSPLAT_DRIVERS_SOFTWARE         50008
#define QSPLAT_DRIVERS_SOFTWARE_TILES_GLDRAWPIXELS 50009
#define QSPLAT_DRIVERS_SOFTWARE_TILES   50010
#define QSPLAT_DRIVERS_SOFTWARE_BEST_GLDRAWPIXELS 50011
#define QSPLAT_DRIVERS_SOFTWARE_BEST    50012
#define IDS_FILTERSTRING                57666

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40035
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
